/*
 * This file is generated by jOOQ.
*/
package com.ycf.dao.tables;


import com.ycf.dao.Keys;
import com.ycf.dao.System;
import com.ycf.dao.tables.records.ApplyInfoRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplyInfo extends TableImpl<ApplyInfoRecord> {

    private static final long serialVersionUID = -1631132849;

    /**
     * The reference instance of <code>system.apply_info</code>
     */
    public static final ApplyInfo APPLY_INFO = new ApplyInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ApplyInfoRecord> getRecordType() {
        return ApplyInfoRecord.class;
    }

    /**
     * The column <code>system.apply_info.apply_id</code>. 申请ID
     */
    public final TableField<ApplyInfoRecord, String> APPLY_ID = createField("apply_id", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "申请ID");

    /**
     * The column <code>system.apply_info.apply_title</code>. 申请标题
     */
    public final TableField<ApplyInfoRecord, String> APPLY_TITLE = createField("apply_title", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "申请标题");

    /**
     * The column <code>system.apply_info.apply_user</code>. 申请人
     */
    public final TableField<ApplyInfoRecord, String> APPLY_USER = createField("apply_user", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "申请人");

    /**
     * The column <code>system.apply_info.apply_time</code>. 申请时间
     */
    public final TableField<ApplyInfoRecord, Timestamp> APPLY_TIME = createField("apply_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "申请时间");

    /**
     * The column <code>system.apply_info.status</code>. 状态&gt;0:完成 1:待审批 2:驳回
     */
    public final TableField<ApplyInfoRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "状态>0:完成 1:待审批 2:驳回");

    /**
     * The column <code>system.apply_info.reject_msg</code>. 驳回信息
     */
    public final TableField<ApplyInfoRecord, String> REJECT_MSG = createField("reject_msg", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "驳回信息");

    /**
     * The column <code>system.apply_info.data</code>. 数据
     */
    public final TableField<ApplyInfoRecord, byte[]> DATA = createField("data", org.jooq.impl.SQLDataType.BLOB, this, "数据");

    /**
     * Create a <code>system.apply_info</code> table reference
     */
    public ApplyInfo() {
        this("apply_info", null);
    }

    /**
     * Create an aliased <code>system.apply_info</code> table reference
     */
    public ApplyInfo(String alias) {
        this(alias, APPLY_INFO);
    }

    private ApplyInfo(String alias, Table<ApplyInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private ApplyInfo(String alias, Table<ApplyInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return System.SYSTEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ApplyInfoRecord> getPrimaryKey() {
        return Keys.KEY_APPLY_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ApplyInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<ApplyInfoRecord>>asList(Keys.KEY_APPLY_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyInfo as(String alias) {
        return new ApplyInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ApplyInfo rename(String name) {
        return new ApplyInfo(name, null);
    }
}
