/*
 * This file is generated by jOOQ.
*/
package com.ycf.dao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplyInfo implements Serializable {

    private static final long serialVersionUID = -251805661;

    private String    applyId;
    private String    proType;
    private String    applyCar;
    private String    applyUser;
    private String    loanVal;
    private Timestamp applyTime;
    private Integer   status;
    private String    rejectMsg;
    private byte[]    data;

    public ApplyInfo() {}

    public ApplyInfo(ApplyInfo value) {
        this.applyId = value.applyId;
        this.proType = value.proType;
        this.applyCar = value.applyCar;
        this.applyUser = value.applyUser;
        this.loanVal = value.loanVal;
        this.applyTime = value.applyTime;
        this.status = value.status;
        this.rejectMsg = value.rejectMsg;
        this.data = value.data;
    }

    public ApplyInfo(
        String    applyId,
        String    proType,
        String    applyCar,
        String    applyUser,
        String    loanVal,
        Timestamp applyTime,
        Integer   status,
        String    rejectMsg,
        byte[]    data
    ) {
        this.applyId = applyId;
        this.proType = proType;
        this.applyCar = applyCar;
        this.applyUser = applyUser;
        this.loanVal = loanVal;
        this.applyTime = applyTime;
        this.status = status;
        this.rejectMsg = rejectMsg;
        this.data = data;
    }

    public String getApplyId() {
        return this.applyId;
    }

    public void setApplyId(String applyId) {
        this.applyId = applyId;
    }

    public String getProType() {
        return this.proType;
    }

    public void setProType(String proType) {
        this.proType = proType;
    }

    public String getApplyCar() {
        return this.applyCar;
    }

    public void setApplyCar(String applyCar) {
        this.applyCar = applyCar;
    }

    public String getApplyUser() {
        return this.applyUser;
    }

    public void setApplyUser(String applyUser) {
        this.applyUser = applyUser;
    }

    public String getLoanVal() {
        return this.loanVal;
    }

    public void setLoanVal(String loanVal) {
        this.loanVal = loanVal;
    }

    public Timestamp getApplyTime() {
        return this.applyTime;
    }

    public void setApplyTime(Timestamp applyTime) {
        this.applyTime = applyTime;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getRejectMsg() {
        return this.rejectMsg;
    }

    public void setRejectMsg(String rejectMsg) {
        this.rejectMsg = rejectMsg;
    }

    public byte[] getData() {
        return this.data;
    }

    public void setData(byte... data) {
        this.data = data;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApplyInfo (");

        sb.append(applyId);
        sb.append(", ").append(proType);
        sb.append(", ").append(applyCar);
        sb.append(", ").append(applyUser);
        sb.append(", ").append(loanVal);
        sb.append(", ").append(applyTime);
        sb.append(", ").append(status);
        sb.append(", ").append(rejectMsg);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
