/*
 * This file is generated by jOOQ.
*/
package com.ycf.dao.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplyInfo implements Serializable {

    private static final long serialVersionUID = 1242417047;

    private String    applyId;
    private String    applyTitle;
    private String    applyUser;
    private Timestamp applyTime;
    private Integer   status;
    private String    rejectMsg;
    private byte[]    data;

    public ApplyInfo() {}

    public ApplyInfo(ApplyInfo value) {
        this.applyId = value.applyId;
        this.applyTitle = value.applyTitle;
        this.applyUser = value.applyUser;
        this.applyTime = value.applyTime;
        this.status = value.status;
        this.rejectMsg = value.rejectMsg;
        this.data = value.data;
    }

    public ApplyInfo(
        String    applyId,
        String    applyTitle,
        String    applyUser,
        Timestamp applyTime,
        Integer   status,
        String    rejectMsg,
        byte[]    data
    ) {
        this.applyId = applyId;
        this.applyTitle = applyTitle;
        this.applyUser = applyUser;
        this.applyTime = applyTime;
        this.status = status;
        this.rejectMsg = rejectMsg;
        this.data = data;
    }

    public String getApplyId() {
        return this.applyId;
    }

    public void setApplyId(String applyId) {
        this.applyId = applyId;
    }

    public String getApplyTitle() {
        return this.applyTitle;
    }

    public void setApplyTitle(String applyTitle) {
        this.applyTitle = applyTitle;
    }

    public String getApplyUser() {
        return this.applyUser;
    }

    public void setApplyUser(String applyUser) {
        this.applyUser = applyUser;
    }

    public Timestamp getApplyTime() {
        return this.applyTime;
    }

    public void setApplyTime(Timestamp applyTime) {
        this.applyTime = applyTime;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getRejectMsg() {
        return this.rejectMsg;
    }

    public void setRejectMsg(String rejectMsg) {
        this.rejectMsg = rejectMsg;
    }

    public byte[] getData() {
        return this.data;
    }

    public void setData(byte... data) {
        this.data = data;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApplyInfo (");

        sb.append(applyId);
        sb.append(", ").append(applyTitle);
        sb.append(", ").append(applyUser);
        sb.append(", ").append(applyTime);
        sb.append(", ").append(status);
        sb.append(", ").append(rejectMsg);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
