/*
 * This file is generated by jOOQ.
*/
package com.ycf.dao;


import com.ycf.dao.tables.ApplyInfo;
import com.ycf.dao.tables.TmUser;
import com.ycf.dao.tables.records.ApplyInfoRecord;
import com.ycf.dao.tables.records.TmUserRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>system</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ApplyInfoRecord> KEY_APPLY_INFO_PRIMARY = UniqueKeys0.KEY_APPLY_INFO_PRIMARY;
    public static final UniqueKey<TmUserRecord> KEY_TM_USER_PRIMARY = UniqueKeys0.KEY_TM_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ApplyInfoRecord> KEY_APPLY_INFO_PRIMARY = createUniqueKey(ApplyInfo.APPLY_INFO, "KEY_apply_info_PRIMARY", ApplyInfo.APPLY_INFO.APPLY_ID);
        public static final UniqueKey<TmUserRecord> KEY_TM_USER_PRIMARY = createUniqueKey(TmUser.TM_USER, "KEY_tm_user_PRIMARY", TmUser.TM_USER.USER_ID);
    }
}
