/*
 * This file is generated by jOOQ.
*/
package com.ycf.dao.tables.records;


import com.ycf.dao.tables.ApplyInfo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplyInfoRecord extends UpdatableRecordImpl<ApplyInfoRecord> implements Record7<String, String, String, Timestamp, Integer, String, byte[]> {

    private static final long serialVersionUID = 2074756965;

    /**
     * Setter for <code>system.apply_info.apply_id</code>. 申请ID
     */
    public void setApplyId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>system.apply_info.apply_id</code>. 申请ID
     */
    public String getApplyId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>system.apply_info.apply_title</code>. 申请标题
     */
    public void setApplyTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>system.apply_info.apply_title</code>. 申请标题
     */
    public String getApplyTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>system.apply_info.apply_user</code>. 申请人
     */
    public void setApplyUser(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>system.apply_info.apply_user</code>. 申请人
     */
    public String getApplyUser() {
        return (String) get(2);
    }

    /**
     * Setter for <code>system.apply_info.apply_time</code>. 申请时间
     */
    public void setApplyTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>system.apply_info.apply_time</code>. 申请时间
     */
    public Timestamp getApplyTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>system.apply_info.status</code>. 状态&gt;0:完成 1:待审批 2:驳回
     */
    public void setStatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>system.apply_info.status</code>. 状态&gt;0:完成 1:待审批 2:驳回
     */
    public Integer getStatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>system.apply_info.reject_msg</code>. 驳回信息
     */
    public void setRejectMsg(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>system.apply_info.reject_msg</code>. 驳回信息
     */
    public String getRejectMsg() {
        return (String) get(5);
    }

    /**
     * Setter for <code>system.apply_info.data</code>. 数据
     */
    public void setData(byte... value) {
        set(6, value);
    }

    /**
     * Getter for <code>system.apply_info.data</code>. 数据
     */
    public byte[] getData() {
        return (byte[]) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Timestamp, Integer, String, byte[]> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Timestamp, Integer, String, byte[]> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ApplyInfo.APPLY_INFO.APPLY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ApplyInfo.APPLY_INFO.APPLY_TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ApplyInfo.APPLY_INFO.APPLY_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ApplyInfo.APPLY_INFO.APPLY_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ApplyInfo.APPLY_INFO.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ApplyInfo.APPLY_INFO.REJECT_MSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field7() {
        return ApplyInfo.APPLY_INFO.DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getApplyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getApplyTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getApplyUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getApplyTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRejectMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value7() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyInfoRecord value1(String value) {
        setApplyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyInfoRecord value2(String value) {
        setApplyTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyInfoRecord value3(String value) {
        setApplyUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyInfoRecord value4(Timestamp value) {
        setApplyTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyInfoRecord value5(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyInfoRecord value6(String value) {
        setRejectMsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyInfoRecord value7(byte... value) {
        setData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplyInfoRecord values(String value1, String value2, String value3, Timestamp value4, Integer value5, String value6, byte[] value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplyInfoRecord
     */
    public ApplyInfoRecord() {
        super(ApplyInfo.APPLY_INFO);
    }

    /**
     * Create a detached, initialised ApplyInfoRecord
     */
    public ApplyInfoRecord(String applyId, String applyTitle, String applyUser, Timestamp applyTime, Integer status, String rejectMsg, byte[] data) {
        super(ApplyInfo.APPLY_INFO);

        set(0, applyId);
        set(1, applyTitle);
        set(2, applyUser);
        set(3, applyTime);
        set(4, status);
        set(5, rejectMsg);
        set(6, data);
    }
}
