/*
 * This file is generated by jOOQ.
*/
package com.ycf.dao.tables.daos;


import com.ycf.dao.tables.ApplyInfo;
import com.ycf.dao.tables.records.ApplyInfoRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplyInfoDao extends DAOImpl<ApplyInfoRecord, com.ycf.dao.tables.pojos.ApplyInfo, String> {

    /**
     * Create a new ApplyInfoDao without any configuration
     */
    public ApplyInfoDao() {
        super(ApplyInfo.APPLY_INFO, com.ycf.dao.tables.pojos.ApplyInfo.class);
    }

    /**
     * Create a new ApplyInfoDao with an attached configuration
     */
    public ApplyInfoDao(Configuration configuration) {
        super(ApplyInfo.APPLY_INFO, com.ycf.dao.tables.pojos.ApplyInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.ycf.dao.tables.pojos.ApplyInfo object) {
        return object.getApplyId();
    }

    /**
     * Fetch records that have <code>apply_id IN (values)</code>
     */
    public List<com.ycf.dao.tables.pojos.ApplyInfo> fetchByApplyId(String... values) {
        return fetch(ApplyInfo.APPLY_INFO.APPLY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>apply_id = value</code>
     */
    public com.ycf.dao.tables.pojos.ApplyInfo fetchOneByApplyId(String value) {
        return fetchOne(ApplyInfo.APPLY_INFO.APPLY_ID, value);
    }

    /**
     * Fetch records that have <code>apply_title IN (values)</code>
     */
    public List<com.ycf.dao.tables.pojos.ApplyInfo> fetchByApplyTitle(String... values) {
        return fetch(ApplyInfo.APPLY_INFO.APPLY_TITLE, values);
    }

    /**
     * Fetch records that have <code>apply_user IN (values)</code>
     */
    public List<com.ycf.dao.tables.pojos.ApplyInfo> fetchByApplyUser(String... values) {
        return fetch(ApplyInfo.APPLY_INFO.APPLY_USER, values);
    }

    /**
     * Fetch records that have <code>apply_time IN (values)</code>
     */
    public List<com.ycf.dao.tables.pojos.ApplyInfo> fetchByApplyTime(Timestamp... values) {
        return fetch(ApplyInfo.APPLY_INFO.APPLY_TIME, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.ycf.dao.tables.pojos.ApplyInfo> fetchByStatus(Integer... values) {
        return fetch(ApplyInfo.APPLY_INFO.STATUS, values);
    }

    /**
     * Fetch records that have <code>reject_msg IN (values)</code>
     */
    public List<com.ycf.dao.tables.pojos.ApplyInfo> fetchByRejectMsg(String... values) {
        return fetch(ApplyInfo.APPLY_INFO.REJECT_MSG, values);
    }

    /**
     * Fetch records that have <code>data IN (values)</code>
     */
    public List<com.ycf.dao.tables.pojos.ApplyInfo> fetchByData(byte[]... values) {
        return fetch(ApplyInfo.APPLY_INFO.DATA, values);
    }
}
